#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### HELPER FUNCTIONS ###

def int_to_bytes(x: int) -> str:
    return x.to_bytes((x.bit_length() + 7) // 8, 'little').decode('latin1')

### YOUR CODE STARTS HERE ###

# Program start:
p.start()

# Example send:
p.send('test\n')

# Example receive:
assert p.recv(5) == 'test\n'

### YOUR CODE ENDS HERE ###
